#
# S3 downloader related config below
#

# loglevel, 3 is default, 0 - no log at all, 5 - log all messages (including SQL strings)
loglevel: 3

# log mode: duplicate, file, 
logmode: duplicate


# AWS S3 bucket name to download stuff from
s3_bucket: 'some_bucket'

# target folder for downloaded stuff
download_folder: stage

# delete remote files or not
delete_remote_files: True

#
# S3 log parsing related stuff below
#

# sqlite database file
db_file: '<some_sqlite_file>.db'

# table name for the cloud front access logs
cf_table: '<table_name>'

# folder where logs to be processed located
logs_folder: 'logfolder'

# folder to move processed log files
bkp_folder: 'logfolder\.processed'

#
# Locations related settings
# 

# Warning: the location script reuses cf_table and db_file settings

# column name in cf_table with ip adress
ip_column: '<ip column>'